services:
  - type: web
    name: ai-image-generator
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8501
      - key: HF_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
    healthCheckPath: /_stcore/health
    autoDeploy: true
